name:                bowling-haskell
version:             0.1.0.0
github:              "MarkDucommun/bowling-haskell"
license:             BSD3
author:              "Mark Ducommun"
maintainer:          "ducommun.mark@gmail.com"
copyright:           "2018 Mark Ducommun"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MarkDucommun/bowling-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - network

executables:
  bowling-server-exe:
    main:                Main.hs
    source-dirs:         bowling-server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - bowling-haskell

tests:
  bowling-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bowling-haskell
    - hspec
